/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/24-3-24/': RouteRecordInfo<
      '/posts/24-3-24/',
      '/posts/24-3-24',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/clean-the-system/': RouteRecordInfo<
      '/posts/clean-the-system/',
      '/posts/clean-the-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/comments-on-texmacs-and-mogan-editor/': RouteRecordInfo<
      '/posts/comments-on-texmacs-and-mogan-editor/',
      '/posts/comments-on-texmacs-and-mogan-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/compile-llvm/': RouteRecordInfo<
      '/posts/compile-llvm/',
      '/posts/compile-llvm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cxx-config/': RouteRecordInfo<
      '/posts/cxx-config/',
      '/posts/cxx-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/data-lab/': RouteRecordInfo<
      '/posts/data-lab/',
      '/posts/data-lab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/do-not-recommend-edge-in-2024/': RouteRecordInfo<
      '/posts/do-not-recommend-edge-in-2024/',
      '/posts/do-not-recommend-edge-in-2024',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/du-le-si/': RouteRecordInfo<
      '/posts/du-le-si/',
      '/posts/du-le-si',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/huawei-smartphone-optimization/': RouteRecordInfo<
      '/posts/huawei-smartphone-optimization/',
      '/posts/huawei-smartphone-optimization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/latex-config/': RouteRecordInfo<
      '/posts/latex-config/',
      '/posts/latex-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/lumia-650-review/': RouteRecordInfo<
      '/posts/lumia-650-review/',
      '/posts/lumia-650-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/malloc-lab/': RouteRecordInfo<
      '/posts/malloc-lab/',
      '/posts/malloc-lab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ocaml-riscv/': RouteRecordInfo<
      '/posts/ocaml-riscv/',
      '/posts/ocaml-riscv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/os-lab-1/': RouteRecordInfo<
      '/posts/os-lab-1/',
      '/posts/os-lab-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/os-lab-2/': RouteRecordInfo<
      '/posts/os-lab-2/',
      '/posts/os-lab-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/os-lab-3/': RouteRecordInfo<
      '/posts/os-lab-3/',
      '/posts/os-lab-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/os-lab-4/': RouteRecordInfo<
      '/posts/os-lab-4/',
      '/posts/os-lab-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/os-lab-5/': RouteRecordInfo<
      '/posts/os-lab-5/',
      '/posts/os-lab-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pkuthesis-doc/': RouteRecordInfo<
      '/posts/pkuthesis-doc/',
      '/posts/pkuthesis-doc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pkuthesis-doc-1.0/': RouteRecordInfo<
      '/posts/pkuthesis-doc-1.0/',
      '/posts/pkuthesis-doc-1/0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pkuthesis-doc-pre-1.0/': RouteRecordInfo<
      '/posts/pkuthesis-doc-pre-1.0/',
      '/posts/pkuthesis-doc-pre-1/0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/proxy-lab/': RouteRecordInfo<
      '/posts/proxy-lab/',
      '/posts/proxy-lab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/risk/': RouteRecordInfo<
      '/posts/risk/',
      '/posts/risk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/setup-a-forge-server/': RouteRecordInfo<
      '/posts/setup-a-forge-server/',
      '/posts/setup-a-forge-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/setup-a-paper-server/': RouteRecordInfo<
      '/posts/setup-a-paper-server/',
      '/posts/setup-a-paper-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/setup-jos-lab-environment/': RouteRecordInfo<
      '/posts/setup-jos-lab-environment/',
      '/posts/setup-jos-lab-environment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/setup-static-blog/': RouteRecordInfo<
      '/posts/setup-static-blog/',
      '/posts/setup-static-blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/stainless-rocket/': RouteRecordInfo<
      '/posts/stainless-rocket/',
      '/posts/stainless-rocket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/thunder/': RouteRecordInfo<
      '/posts/thunder/',
      '/posts/thunder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/thunder-2/': RouteRecordInfo<
      '/posts/thunder-2/',
      '/posts/thunder-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/todo/': RouteRecordInfo<
      '/posts/todo/',
      '/posts/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/typesetting/': RouteRecordInfo<
      '/posts/typesetting/',
      '/posts/typesetting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/visual-novels/': RouteRecordInfo<
      '/posts/visual-novels/',
      '/posts/visual-novels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/waydroid-on-wsl2/': RouteRecordInfo<
      '/posts/waydroid-on-wsl2/',
      '/posts/waydroid-on-wsl2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/why-mp-main-indirect-call/': RouteRecordInfo<
      '/posts/why-mp-main-indirect-call/',
      '/posts/why-mp-main-indirect-call',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/why-sys-exofork-inlined/': RouteRecordInfo<
      '/posts/why-sys-exofork-inlined/',
      '/posts/why-sys-exofork-inlined',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_vue@3.5.22_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.13_@babel+parse_d4855280fd7189c735304a00e6e183c1/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_vue@3.5.22_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_vue@3.5.22_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/24-3-24/index.md': {
      routes:
        | '/posts/24-3-24/'
      views:
        | never
    }
    'pages/posts/clean-the-system/index.md': {
      routes:
        | '/posts/clean-the-system/'
      views:
        | never
    }
    'pages/posts/comments-on-texmacs-and-mogan-editor/index.md': {
      routes:
        | '/posts/comments-on-texmacs-and-mogan-editor/'
      views:
        | never
    }
    'pages/posts/compile-llvm/index.md': {
      routes:
        | '/posts/compile-llvm/'
      views:
        | never
    }
    'pages/posts/cxx-config/index.md': {
      routes:
        | '/posts/cxx-config/'
      views:
        | never
    }
    'pages/posts/data-lab/index.md': {
      routes:
        | '/posts/data-lab/'
      views:
        | never
    }
    'pages/posts/do-not-recommend-edge-in-2024/index.md': {
      routes:
        | '/posts/do-not-recommend-edge-in-2024/'
      views:
        | never
    }
    'pages/posts/du-le-si/index.md': {
      routes:
        | '/posts/du-le-si/'
      views:
        | never
    }
    'pages/posts/huawei-smartphone-optimization/index.md': {
      routes:
        | '/posts/huawei-smartphone-optimization/'
      views:
        | never
    }
    'pages/posts/latex-config/index.md': {
      routes:
        | '/posts/latex-config/'
      views:
        | never
    }
    'pages/posts/lumia-650-review/index.md': {
      routes:
        | '/posts/lumia-650-review/'
      views:
        | never
    }
    'pages/posts/malloc-lab/index.md': {
      routes:
        | '/posts/malloc-lab/'
      views:
        | never
    }
    'pages/posts/ocaml-riscv/index.md': {
      routes:
        | '/posts/ocaml-riscv/'
      views:
        | never
    }
    'pages/posts/os-lab-1/index.md': {
      routes:
        | '/posts/os-lab-1/'
      views:
        | never
    }
    'pages/posts/os-lab-2/index.md': {
      routes:
        | '/posts/os-lab-2/'
      views:
        | never
    }
    'pages/posts/os-lab-3/index.md': {
      routes:
        | '/posts/os-lab-3/'
      views:
        | never
    }
    'pages/posts/os-lab-4/index.md': {
      routes:
        | '/posts/os-lab-4/'
      views:
        | never
    }
    'pages/posts/os-lab-5/index.md': {
      routes:
        | '/posts/os-lab-5/'
      views:
        | never
    }
    'pages/posts/pkuthesis-doc/index.md': {
      routes:
        | '/posts/pkuthesis-doc/'
      views:
        | never
    }
    'pages/posts/pkuthesis-doc-1.0/index.md': {
      routes:
        | '/posts/pkuthesis-doc-1.0/'
      views:
        | never
    }
    'pages/posts/pkuthesis-doc-pre-1.0/index.md': {
      routes:
        | '/posts/pkuthesis-doc-pre-1.0/'
      views:
        | never
    }
    'pages/posts/proxy-lab/index.md': {
      routes:
        | '/posts/proxy-lab/'
      views:
        | never
    }
    'pages/posts/risk/index.md': {
      routes:
        | '/posts/risk/'
      views:
        | never
    }
    'pages/posts/setup-a-forge-server/index.md': {
      routes:
        | '/posts/setup-a-forge-server/'
      views:
        | never
    }
    'pages/posts/setup-a-paper-server/index.md': {
      routes:
        | '/posts/setup-a-paper-server/'
      views:
        | never
    }
    'pages/posts/setup-jos-lab-environment/index.md': {
      routes:
        | '/posts/setup-jos-lab-environment/'
      views:
        | never
    }
    'pages/posts/setup-static-blog/index.md': {
      routes:
        | '/posts/setup-static-blog/'
      views:
        | never
    }
    'pages/posts/stainless-rocket/index.md': {
      routes:
        | '/posts/stainless-rocket/'
      views:
        | never
    }
    'pages/posts/thunder/index.md': {
      routes:
        | '/posts/thunder/'
      views:
        | never
    }
    'pages/posts/thunder-2/index.md': {
      routes:
        | '/posts/thunder-2/'
      views:
        | never
    }
    'pages/posts/todo/index.md': {
      routes:
        | '/posts/todo/'
      views:
        | never
    }
    'pages/posts/typesetting/index.md': {
      routes:
        | '/posts/typesetting/'
      views:
        | never
    }
    'pages/posts/visual-novels/index.md': {
      routes:
        | '/posts/visual-novels/'
      views:
        | never
    }
    'pages/posts/waydroid-on-wsl2/index.md': {
      routes:
        | '/posts/waydroid-on-wsl2/'
      views:
        | never
    }
    'pages/posts/why-mp-main-indirect-call/index.md': {
      routes:
        | '/posts/why-mp-main-indirect-call/'
      views:
        | never
    }
    'pages/posts/why-sys-exofork-inlined/index.md': {
      routes:
        | '/posts/why-sys-exofork-inlined/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
