/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/24-3-24/': RouteRecordInfo<'/posts/24-3-24/', '/posts/24-3-24', Record<never, never>, Record<never, never>>,
    '/posts/cxx-config/': RouteRecordInfo<'/posts/cxx-config/', '/posts/cxx-config', Record<never, never>, Record<never, never>>,
    '/posts/cxx-config/index3': RouteRecordInfo<'/posts/cxx-config/index3', '/posts/cxx-config/index3', Record<never, never>, Record<never, never>>,
    '/posts/data-lab/': RouteRecordInfo<'/posts/data-lab/', '/posts/data-lab', Record<never, never>, Record<never, never>>,
    '/posts/latex-config/': RouteRecordInfo<'/posts/latex-config/', '/posts/latex-config', Record<never, never>, Record<never, never>>,
    '/posts/malloc-lab/': RouteRecordInfo<'/posts/malloc-lab/', '/posts/malloc-lab', Record<never, never>, Record<never, never>>,
    '/posts/os-lab-1/': RouteRecordInfo<'/posts/os-lab-1/', '/posts/os-lab-1', Record<never, never>, Record<never, never>>,
    '/posts/os-lab-2/': RouteRecordInfo<'/posts/os-lab-2/', '/posts/os-lab-2', Record<never, never>, Record<never, never>>,
    '/posts/os-lab-3/': RouteRecordInfo<'/posts/os-lab-3/', '/posts/os-lab-3', Record<never, never>, Record<never, never>>,
    '/posts/os-lab-4/': RouteRecordInfo<'/posts/os-lab-4/', '/posts/os-lab-4', Record<never, never>, Record<never, never>>,
    '/posts/os-lab-5/': RouteRecordInfo<'/posts/os-lab-5/', '/posts/os-lab-5', Record<never, never>, Record<never, never>>,
    '/posts/proxy-lab/': RouteRecordInfo<'/posts/proxy-lab/', '/posts/proxy-lab', Record<never, never>, Record<never, never>>,
    '/posts/risk/': RouteRecordInfo<'/posts/risk/', '/posts/risk', Record<never, never>, Record<never, never>>,
    '/posts/setup-a-forge-server/': RouteRecordInfo<'/posts/setup-a-forge-server/', '/posts/setup-a-forge-server', Record<never, never>, Record<never, never>>,
    '/posts/setup-a-paper-server/': RouteRecordInfo<'/posts/setup-a-paper-server/', '/posts/setup-a-paper-server', Record<never, never>, Record<never, never>>,
    '/posts/setup-jos-lab-environment/': RouteRecordInfo<'/posts/setup-jos-lab-environment/', '/posts/setup-jos-lab-environment', Record<never, never>, Record<never, never>>,
    '/posts/setup-static-blog/': RouteRecordInfo<'/posts/setup-static-blog/', '/posts/setup-static-blog', Record<never, never>, Record<never, never>>,
    '/posts/thunder/': RouteRecordInfo<'/posts/thunder/', '/posts/thunder', Record<never, never>, Record<never, never>>,
    '/posts/why-mp-maun-indirect-call/': RouteRecordInfo<'/posts/why-mp-maun-indirect-call/', '/posts/why-mp-maun-indirect-call', Record<never, never>, Record<never, never>>,
    '/posts/why-sys-exofork-inlined/': RouteRecordInfo<'/posts/why-sys-exofork-inlined/', '/posts/why-sys-exofork-inlined', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
