name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true
      - name: Install PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Blog
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./dist"

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-26.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
